import localFont from "next/font/local";
import "./globals.css";
import { DisplayAhadith } from "@/components/DisplayAhadith";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "7ifd wa mouraga3a",
  description: "Generated by ...",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-slate-700`}
      >
        {children}
      </body>
    </html>
  );
}
